---
abstract: 'File::ShareDir with PAR support'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::ShareDir::PAR
name: File-ShareDir-PAR
no_index:
  directory:
    - share
    - foo
    - share
    - inc
    - t
requires:
  Carp: 0
  Class::Inspector: 1.12
  File::Path: 0
  File::ShareDir: 0
  File::Spec: 0.80
  Params::Util: 0.07
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
